name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.22
      - name: Build
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)"
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.22
      - name: Start
        run: |
          nohup go run . > server.log 2>&1 &
          sleep 10
      - name: check
        run: |
          curl --fail ws://localhost:9999/ || (echo "服务未启动" && exit 1)
      - name: Test
        run: |
          go test -v ./...