name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.22
      - name: Build
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)"
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Start the WebSocket server
        run: |
          nohup go run . > server.log 2>&1 &
          sleep 10  # 等待服务启动

      - name: Install websocat
        run: |
          curl -LO https://github.com/vi/websocat/releases/download/v1.7.0/websocat_amd64-linux
          chmod +x websocat_amd64-linux
          mv websocat_amd64-linux /usr/local/bin/websocat

      - name: Check WebSocket server
        run: |
          websocat ws://localhost:9999/ || (echo "WebSocket 服务未启动" && exit 1)

      - name: Run Tests
        run: |
          go test -v ./...
